[default]
show=false
host="0.0.0.0"
port=8123
graphql_port=8124
testdata=true

    [default.uvicorn]
    reload="@bool @jinja {{this.editable}}"

    [default.logging]
    show_sql_commands=false

    [default.db]
    data_dir = "@jinja {% if this.editable %}{{this.pkg_root}}/data{% else %}{{this.user_data_dir}}{% endif %}"
    url = "@jinja sqlite+pysqlite:///{{this.db.data_dir}}/db.sqlite"

[testing]
testdata=true
initial_admin_password="admin"
session_secret="setting this allows session reuse across backend restarts"