"""add 'attached'

Revision ID: 930a51864adb
Revises: c6e034666a4b
Create Date: 2023-10-15 10:57:24.837983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930a51864adb'
down_revision = 'c6e034666a4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('attached', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Task', 'attached')
    # ### end Alembic commands ###
